src/state/megaStore.tsx

kind of hard to debug this because the window and console go away lol
it only runs in chrome if the user has interacted with the page. if you return a value from the function you should see a prompt proving it does run

stop mutiny_wallet on unload

---

src/components/AmountEditable.tsx
src/components/layout/Radio.tsx
src/routes/Send.tsx

this should fix the errors when scanning unified qrs / receive with no input... basically I was trying to focus the text input of the amount input even when the modal wasn't open, so it would throw an error
also caught a bug while doing this where the fee estimator for onchain was throwing errors that I wasn't catching, now added an error box possibly related to #195 stuff @benalleng

Fix amountbox

---

src/routes/Scanner.tsx
src/routes/Send.tsx
src/utils/useCopy.ts

I believe this should fix #250 
ios is weird where it doesn't allow you to use your own UI for paste, it wants to open up a "native" thingy that the user has to click
before, if the user clicked the mutiny paste button, allowed paste, and then clicked the mutiny paste button again you get the noisy error. now we catch that error instead of showing it. the ui is pretty obvious after a few taps that you really gotta hit the "native" paste tip

catch paste errors

---

src/logic/browserCompatibility.ts

Fixes https://github.com/MutinyWallet/mutiny-web/issues/246
Reproduce via `google-chrome --js-flags="--jitless"`
---
In your original code:
```
try {
if (
typeof WebAssembly === "object" &&
typeof WebAssembly.instantiate === "function"
) {
const module = new WebAssembly.Module(
Uint8Array.of(0x0, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00)
);
if (module instanceof WebAssembly.Module) {
// continue
} else {
throw new Error("WebAssembly is not supported.");
}
}
} catch (e) {
console.error(e);
throw new Error("WebAssembly is not supported.");
}
```
You are first checking if WebAssembly is an object and if it has a method called instantiate. If either of these checks fails, it should not enter the if block and go straight to the catch block, where it would throw an error "WebAssembly is not …

Fix wasm check

---

src/components/BalanceBox.tsx
src/routes/Swap.tsx
src/state/megaStore.tsx

ChatGPT: Suspense and asynchronous operations: You are using Suspense and FullscreenLoader to handle asynchronous operations. If an asynchronous operation is ongoing when you navigate away, and then it completes and changes the state after you have navigated, this could potentially cause a re-render.
---
There was a time race that kept calling the fee estimator like 3-4 times in the span of navigating back to home. For some reason, doing it so fast causes it to call many times. Waiting on the success screen for a few seconds and then hitting nice will cause it to have a "not enough funds error" in the log. Then when clicking on the swap button causes a "dangit" error because not enough funds for the operation. 
This hopefully fixes all the weird transitions around swaps but there's an …

Swap fixes

---

src/components/App.tsx

Closes #172
shows a network subheading when not on mainnet

Add network subheading

---

src/components/Activity.tsx
src/components/AmountEditable.tsx
src/components/DetailsModal.tsx
src/components/LiquidityMonitor.tsx
src/components/Logs.tsx
src/components/Restart.tsx
src/logic/mutinyWalletSetup.ts
src/routes/Activity.tsx
src/routes/Receive.tsx
src/routes/Scanner.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/state/megaStore.tsx

less noisy if you ignore the last commit, which is an attempt to catch all of these errors in the first place so none of this other defensive logic needs to be triggered
the actual very bad problem with the swap logic is that a potentially error-throwing function was being retriggered every time the state changed. the state changes when the balance goes down, which caused it to try and get the fee again.
IF this just resulted in them landing on the error page, then they'd be okay, because when they click "dangit" that reloads the page so they get a brand new `mutiny_wallet` instance and the old stuff is blown away
BUT because the error page unmounted the old mutiny_wallet without stopping it, AND then the swap logic auto-redirected to the home page, a new mutiny_wallet was getting …

Multi instance defense

---

src/components/Reader.tsx

All are not critical, but maybe worth to check/fix it:

fix: await scanner.start()

---

pnpm-lock.yaml
src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/components/BetaWarningModal.tsx
src/logic/browserCompatibility.ts
src/routes/Receive.tsx

Closes #205, closes #260
the functionalitty for the send route remains where it keeps you on the send page without sending you forward
additionally the input is reset back to the initialAmountSats when onClose() so there is not a secret error where the UI would show a different amoun than the input

Enhances onClose() functionality of <AmountEditable />

---

package.json
pnpm-lock.yaml
src/components/DeleteEverything.tsx
src/components/ErrorDisplay.tsx
src/components/ImportExport.tsx
src/components/Logs.tsx
src/components/SetupErrorDisplay.tsx
src/components/layout/index.tsx
src/logic/browserCompatibility.ts
src/logic/mutinyWalletSetup.ts
src/routes/EmergencyKit.tsx
src/routes/Settings.tsx
src/state/megaStore.tsx

relies on https://github.com/MutinyWallet/mutiny-node/pull/616
this covers a few bad error states.
1. if the node manager panics during setup, the error screen will include the "emergency kit" items of import / export, download logs, and delete everything, all of which will now work without a node manager present
2. on regular error screens (which shouldn't really happen anymore because we're catching all errors afaik) there's a link to a new `/emergencykit` route
3. in settings there's also a link to `/emergencykit`
basically, if someone is unable to load at all, they should be able to get to the emergency kit, and if they are able to load and navigate they can get to `/emergencykit` even if they don't have a url bar

add emergency kit and new error states

---

src/components/App.tsx
src/components/LoadingIndicator.tsx
src/logic/mutinyWalletSetup.ts
src/logic/waila.ts
src/routes/Scanner.tsx
src/routes/Send.tsx
src/routes/settings/EmergencyKit.tsx
src/state/megaStore.tsx

it's not exactly beautiful but I think this could be helpful for diagnosing where someone is "stuck" in loading... I couldn't find any obvious way to hook into the wasm load progress, so instead I just made checkpoints for setup to say how far it's gotten
also this defers the waila stuff to the scanner (so only loads when you pull up send or scanner) which should make the home screen load faster by itself
https://github.com/MutinyWallet/mutiny-web/assets/543668/9d2231f4-650e-4bf4-9083-1e6e0c160c69

add loading progress bar

---

src/routes/settings/Backup.tsx
src/routes/settings/index.tsx

not removing encryption for existing encrypted users, just hiding the current CTAs

hide encryption page

---

src/components/Activity.tsx
src/components/ActivityItem.tsx
src/components/Amount.tsx
src/components/AmountEditable.tsx
src/components/BalanceBox.tsx
src/components/successfail/SuccessModal.tsx
src/i18n/en/translations.ts
src/routes/Receive.tsx
src/routes/Send.tsx

first pass at transitioning over to i18n.t('namespace.key') for all copy.
I took a "componentization" approach so as to try and make the typescript file easier to read, let me know if you think you'd like a different approach with how the keys should be organized.
It is not perfect at the moment just a start

Initial transition to translation keys

---

src/routes/Receive.tsx

Will now close the dialog when you select an option from this screen instead of having the user need to click the X afterwards

Close dialog on select receive flavor

---

src/components/BetaWarningModal.tsx
src/components/DecryptDialog.tsx
src/logic/mutinyWalletSetup.ts
src/routes/Swap.tsx
src/routes/settings/Servers.tsx
src/state/megaStore.tsx

the old behavior was to aggressively add all environment variables to the user's localstorage. we would do this on every setup, which, for instance, overwrote a setting if the user deleted a string (like the lsp)
now we only add stuff to a new USER_ prefixed storage key when the user sets a setting to be different than the default value
this makes it possible for us to change default values for users who haven't set custom values
also I refactored a bit and the whole settings stuff is a lot more straightforward now

don't store default settings

---

src/i18n/en/translations.ts
src/routes/Swap.tsx

Closes #400 
amount now calculated as balance + reserve
wanted to avoid just using `amountSats()` incase of an error that isn't caught it will display "+0" instead of showing an amount even though the swap didn't go through

Swap SuccessScreen now accurately displays amount

---

global.d.ts
tsconfig.json

Hi,
If that's okay I'd love to help ! I'll start with some low hanging fruit issues/fixes/optimizations that I see to get to know the codebase
Anyhow, the PR is for the `vite-pwa` types in the `global.d.ts` file. Since you already use the `compilerOptions.types` attribute in the `tsconfig` (and they basically do the same thing) I figured one less file at the root of the project would be better

Move types from global.d.ts to tsconfig.json

---

postcss.config.cjs
vite.config.ts

Just another simple change, moving the config to `vite.config.ts` allows one less file and having types
They aren't used right now and the config will most likely not be needed after the integration of the lightning css engine but still

Move postcss config to vite's config file

---

src/state/megaStore.tsx
vite.config.ts

when I set up existing tab checking I put in 500ms timer to give it extra buffer to catch tabs... 
~~now that we have extra instance detection from the cloud I'm removing the delay~~
apparently cloud detection doesn't help this case. other two points remain:
this 1. speeds up startup times, 2. doesn't seem to miss any existing tabs in my testing anyway so maybe the buffer never helped at all

get rid of delay for existing tab checking

---

package.json
pnpm-lock.yaml

I ran a fresh pnpm install so I would know we have a lockfile in a known good case
from looking at this issue, 6.1 was a mistake, 6.0 is the correct version:
https://github.com/pnpm/pnpm/issues/6648#issuecomment-1588863457
@benalleng @gawlk make sure you guys aren't using one of these bad pnpm versions: v8.6.0, v8.6.1, v7.33.0, that seems to be what introduces the 6.1
I updated the package.json to match cloudflare's installed version of pnpm (which is the main thing we need to keep compatiblity with): https://developers.cloudflare.com/pages/platform/language-support-and-tools/

fresh pnpm install just to make sure

---

justfile

Closes #478 and resolves an error when running `pnpm build` after unlinking

Filter for mutiny-wasm when unlinking

---

src/components/AmountEditable.tsx

Fixes a bug where the hold "DEL" to delete all only worked on Desktop, `PointerEvents` should work on all devices. Additionally did not replace `onMouseLeave` with `onPointerLeave` as it isn't necessary in this logic

Delete all for amountEditable should use PointerEvents

---

src/utils/tags.ts

Fixed the TS error, not sure if you're fans or haters of `switch` though, of course will change to ifs if preferred.
But one weird thing is that the type of `kind` is supposed to be a number in the input and a string in the output. Either the input is badly typed or there might be some bugs in the app you use `kind` somewhere since the return type was lying to you until now
I'll edit this PR after I check which one it is 
EDIT: Kind of overwhelmed for now by the codebase, I'll need some time to figure how to pass through this function and print a `console.log` (to know what's in the original `tag.kind`)

Fix tagToMutinyTag ts error

---

package.json
pnpm-lock.yaml
src/components/AmountEditable.tsx
src/components/ContactForm.tsx
src/components/KitchenSink.tsx
src/components/OnboardWarning.tsx
src/components/layout/Button.tsx
src/components/layout/Misc.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
vite.config.ts

Closes #413 
Rewrites `<Button />` and `<ButtonLink />` to no longer use cva and instead uses classList for most cases. ~~@futurepaul and I have had discussion about avoiding string interpolation in `class={'${props.class}'}` but alas I did not think of a great way to do that here as I found several instances of the button components where they used individual classes.~~
also adds a small fix for a prop bug in the `<Collapser />` component

Rewrite button.tsx to remove class-variance

---

src/i18n/en/translations.ts
src/routes/Send.tsx

Closes #462 
Also included a very obscure catch wherby the send button is disabled if there is and amount in the invoice but it does not equal amountSats() `invoice().amount_sats !== amountSats()` unsure if/how this would ever occur as having the ability to edit the amount is only possible if there is no amount set in the invoice. If it seems unneccessary I'm happy to remove it
This video below is only possible because of some altered logic `isAmountEditable={true}`
[Kazam_screencast_00003.webm](https://github.com/MutinyWallet/mutiny-web/assets/108441023/ee8ce4c9-e24b-4e55-84c5-4fbff41bd5a0)

Clear error after send button disabled and enhance error catches

---

src/routes/Activity.tsx

This makes it so the activity screen will have the top contacts always be the same order (sorted by last used then by name). `get_contacts` was a json object so the ordering would be pretty much random. Now we will get it in a sorted array

Sorted contacts on activtiy screen

---

README.md
package.json

I rather not make this a pre-commit hook for everyone because I don't like that workflow (sometimes I need to do a wip commit that doesn't typecheck yet) but feel free to set it locally

change "lint" to pre-commit and add format

---

.github/workflows/android-staging.yml

People that pull github builds off of package managers might see the prerelease build and get confused about what signet means. This just adds the word test there.

Clarify android prerelease builds as test

---

src/components/AmountEditable.tsx
src/components/ChooseCurrency.tsx
src/routes/settings/index.tsx
src/state/megaStore.tsx

relies on https://github.com/MutinyWallet/mutiny-node/pull/758
works with the addition of mutiny-node#758 such that a new currency is fetched but switching back before the cache timeout keeps the currencies in cache so they can be swapped quickly without querying the coingecko api. The bitcoin currency option still never reaches out to the api.
Also makes the SmallSubtleAmount update when the price changes, this fixes a bug whereby the user could race the price api and set the sats amount before the fiat amount had a chance to be calculated. Production leaves the secondary amount at 0
[!](https://github.com/MutinyWallet/mutiny-web/assets/108441023/5723a9c4-06b3-47ac-bbd1-b52634e3430e)

Currency change no longer requires reload

---

src/routes/settings/Connections.tsx
src/utils/index.ts
src/utils/openLinkProgrammatically.ts

there was an "open app" button that wasn't opening the uri callback because safari was being too aggressive about "pop-up blocking" (safari and other browsers don't want the browser to navigate if not by a user action). by lifting the logic out of capacitor's Browser.open safari is happy now.

fix safari app links

---

src/components/ActivityItem.tsx
src/components/Amount.tsx
src/components/BalanceBox.tsx
src/state/megaStore.tsx

Reverts a change from #503 so that there is not an amount loading indicator.
In combination with https://github.com/MutinyWallet/mutiny-node/pull/764 node version we should be able to never see a load time for instant prices

revert: amount loading logic

---

src/i18n/en/translations.ts
src/routes/settings/Encrypt.tsx

Closes #490 after [Mutiny-node/#727](https://github.com/MutinyWallet/mutiny-node/pull/727) is merged
Adds similar logic to prevent #462 from cropping up here

Encryption password UX

---

src/routes/Send.tsx

We weren't setting the fee after lightning sends so it'd always show `0`

Properly set fees paid on lightning sends

---

src/components/ContactViewer.tsx
src/components/NostrActivity.tsx
src/components/TagEditor.tsx
src/components/layout/Misc.tsx
src/i18n/en/translations.ts
src/logic/waila.ts
src/routes/Send.tsx

Testing autofill tags on contact send
[!](https://github.com/MutinyWallet/mutiny-web/assets/108441023/4a42db39-a21d-4965-b983-70e9dee32628)

Nostr activity and tag support

---

src/state/megaStore.tsx

When it is a fresh wallet they won't have a cached price so it'll be slow to get the price, so we can skip getting the price and just let the interval do it.

Only optimistically get price when balance non-zero

---

src/routes/settings/Channels.tsx

Before we were showing our ln balance as outbound, however for our LN balance we include things like the reserve so it doesn't look like you randomly lose money. This fixes so we actually correctly calculate outbound capacity
Related to #564

Correct outbound calculation

---

src/components/ChooseCurrency.tsx

When pressing the select currency button without selecting an option, it would always reset to USD even if the displayed select option value was another currency
I was able to use state.fiat as the logic for setting the fiat will be done by the time the user gets to this page, no concern of undefined behavior

Currency selector no longer resets to USD on no-selection

---

src/components/NWCBudgetEditor.tsx
src/i18n/en/translations.ts
src/routes/settings/Connections.tsx

Closes #541 
Hides the QR code and nwc string for all reserved NWC profiles ids < 1000
Makes the budget static for nwc of type "Subscription" not just the "Mutiny+ Subscription"
Adds additional info like the resubscribe date

Mutiny+ Subscription hidden QR

---

src/routes/Send.tsx

Closes #594 
Should catch more destination parsing errors relating to things beyond the waila
(also moves some component child-parent organization so that buttons and errors aren't visible before they should be
Something to think about, should consider making a more "user" readable error vs human readable error here?
- more testing to make sure I've caught them all

Display all send fieldDestination errors

---

src/utils/vibrate.ts

when calling `window.navigator.vibrate` on browsers that didn't support it it would throw an error, so we just let Capacitor handle it for us

Use Capacitor for all vibrations

---

src/components/ErrorDisplay.tsx
src/components/layout/Misc.tsx
src/root.tsx

No totally sure what I am doing here but I think this could help.
When `MegaStoreProvider` is mounted it creates an instance of mutiny-node, so if any parent components are changed it would too. So I put the `I18nProvider` inside of it incase that is changing as well as a second `ErrorBoundary` that will handle the `Router`, so if any uncaught errors happen there, we don't create a new instance of mutiny-node.
ChatGPT said it might help

Make MegaStoreProvider higher in root components

---

src/components/ChooseCurrency.tsx
src/state/megaStore.tsx

- Add **Brazilian Real BRL** currency.
- Order list of currencies alphabetically by `value`.

Add Brazilian Real BRL currency

---

src/components/BalanceBox.tsx

A lot of users get confused after a force close they click the swap button but then have 0 balance there. We should only show the button if they have an actual balance, not pending force closes

Hide lightning swap button if on-chain balance is only force closes

---

src/utils/fetchZaps.ts

don't have to halt everything for this error, now we catch it and continue:
here's an example event we were choking on before idk what's specifically wrong with it I don't have nostr loaded into my brain rn

don't throw for failed zap parse

---

src/logic/mutinyWalletSetup.ts

safari logs `Storage may be cleared by the UA under storage pressure.`, chrome logs `Storage will not be cleared except by explicit user action`, but it seems like the right thing to do anyway
Closes #671

ask browser for storage persistence

---

src/components/Amount.tsx

this fixes a regression from #520 
good:
bad:

fix spacing for fiat amounts

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/components/PendingNwc.tsx
src/components/TagEditor.tsx
src/components/layout/Misc.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/settings/Connections.tsx
src/routes/settings/Gift.tsx
src/state/megaStore.tsx
src/utils/tags.ts

needs https://github.com/MutinyWallet/mutiny-node/pull/821/
updated wasm-bindgen generates better types in a few places, which means we can get rid of a this `MutinyTagItem` hack. also caught a couple places where I wasn't checking for undefined

better types thx wasm-bindgen

---

.github/workflows/playwright.yml

Makes it so we will only run on PRs (no reason to run it on merge)
Also makes it so only one will run at a time per PR, this way we'll have a higher likelihood of things not getting borked

Playwright CI improvements

---

ios/App/App.xcodeproj/project.pbxproj
src/utils/fetchZaps.ts

this refactors a bit to make nostr fetching easier to read and catches the error in #710 but doesn't solve it
update: now it does solve it. problem was a user had non-pubkeys in their list of follows

refactor zap fetch and discard non-pubkeys

---

src/state/megaStore.tsx

separates price syncing from balance syncing, sets the price fetch interval to a minute, backs off if it gets errors, and tries to get price on boot even if we have zero balance (so the first receive can be priced in fiat)
seems to be working in my local testing. my apologies to coingecko for all the spam

sync price every minute and backoff if err

---

src/i18n/en/translations.ts
src/routes/Send.tsx

To test I just added the signet lsp to the list of hodl invoice nodes

Add hodl invoice warning

---

src/i18n/en/translations.ts
src/logic/waila.ts
src/routes/Send.tsx

Before if you entered a lightning address the destination would be it lnurl encoded, this will fix for it so show as the normal lightning address.
Also adds the is hodl invoice check for zeuspay addresses

Show lightning address on send screen

---

src/assets/icons/black-close.svg
src/components/IOSbanner.tsx
src/components/index.ts
src/i18n/en/translations.ts
src/routes/Main.tsx
src/routes/Send.tsx
src/routes/settings/Plus.tsx
src/state/megaStore.tsx
src/utils/platform.ts

banner shows up on mobile safari, shouldn't be present on other browsers or on native
link goes to mutiny+ signup if they aren't mutiny+, otherwise goes to testflight page
also added link to testflight from mutiny+ page
also if you scan `app.mutinywallet.com/settings/plus` with the app it should nav to that url now

Mutiny plus plus

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/i18n/en/translations.ts
src/routes/settings/Channels.tsx

[needs #878](https://github.com/MutinyWallet/mutiny-node/pull/878)

list individual channels on channels page

---

Dockerfile
default.conf

Previously if you went to any route that wasn't `/` on a self hosted instance it would fail unless you originally navigated from the `/` route. This fixes so those routes will fallback to the `index.html` so it can get the correct page

Fix nginx for other routes

---

package.json
pnpm-lock.yaml
src/components/Activity.tsx
src/components/ActivityItem.tsx
src/components/ContactForm.tsx
src/components/ContactViewer.tsx
src/components/KitchenSink.tsx
src/components/NWCEditor.tsx
src/components/PendingNwc.tsx
src/i18n/en/translations.ts
src/logic/mutinyWalletSetup.ts
src/routes/Activity.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/utils/gradientHash.ts

requires https://github.com/MutinyWallet/mutiny-node/pull/898
also this change allows us to do contact editing so I added a small amount of that (you can also add a lightning address when creating... good test is to add faucet as a contact: `refund@lnurl-staging.mutinywallet.com`)
didn't go crazy with other possibilities because contacts are going to shift around a lot in the new design

switch Contact to TagItem, handle edit

---

src/components/ErrorDisplay.tsx

When we get this error you just need to refresh the page, so we can just do it automatically.
One potential issue is that if refreshing doesn't fix, it'll be in a refresh loop

Reload page on Wasm error

---

package.json
pnpm-lock.yaml
src/routes/settings/Restore.tsx
src/state/megaStore.tsx

With gluedb, we need to drop all instances of it before trying to init it again. Since we're doing associated functions here, we need to init gluedb out of band since we don't rely on `MutinyWallet` anymore after we stop it. This makes sure we stop mutiny wallet and then drop it then do DB operations.

Drop MutinyWallet before restore

---

android/app/build.gradle
package.json
pnpm-lock.yaml
src/components/KitchenSink.tsx

I'll wait until the morning to deploy.
If anyone wants to go ahead and install the testflight version, that would be great.

v0.5.1 prod release

---

src/components/PendingNwc.tsx

We handle this for auto approvals in the backend but can't for manual. If we've already paid an invoice no real reason to show an error, they've already paid it so only way forward is to skip and go on so this just changes to skip those errors

Skip invoice paid twice error in NWC

---

src/utils/currencies.ts

the new price api doesn't support these, these aren't huge countries so i think it is fine to remove for now, if someone complains we add another provider to the price api to bring them back
COP is now supported which a user requested: #639
test with: https://github.com/MutinyWallet/mutiny-node/pull/936

Remove no-longer supported currencies + add new ones

---

src/routes/Search.tsx
src/utils/fetchZaps.ts

uses primal's search api to search everybody on nostr
when testing on signet you can search mutinynet and you get the refund address
clicking a search result will go to the send screen and add that user to your contacts

add global contact search

---

src/routes/settings/Restore.tsx
src/utils/words.ts

Sets are faster than arrays for lookups: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#performance

Faster lookup of bip39 words

---

src/i18n/en/translations.ts
src/routes/Search.tsx
src/utils/fetchZaps.ts

Adds ability to send to users who only have a lnurl set.
Now shows users without any payment info, but disabled and greyed out.
Also switches to use a set over an array, this should make lookups faster but seems like most of the lag when typing is from the global search, maybe need to delay that by 250ms until the user is done typing

Search Improvements

---

README.md
capacitor.config.ts
e2e/encrypt.spec.ts
e2e/load.spec.ts
e2e/restore.spec.ts
package.json
prettier.config.mjs
tsconfig.json

Also  WHY `tabWidth: 4,` ? :D :D :D  my eyes...

prettier formatting consistency

---

src/i18n/en/translations.ts

The setup fee text is incorrect if receiving on chain.

Clarify setup fee

---

src/i18n/en/translations.ts
src/logic/waila.ts
src/routes/Send.tsx
src/state/megaStore.tsx

supersede #572
fix ci errors
awaiting mutiny-node merge as a dependency for this
> Relies on https://github.com/MutinyWallet/mutiny-node/pull/647 and https://github.com/MutinyWallet/bitcoin-waila/pull/8
> 
> Test with @DanGould's payjoin receiver
> visit https://mutiny.payjoin.org:4433/bip21?amount=0.00066666 to get a bip21
> 
> - [x] waila part
> - [x] node part
-- @benalleng

Payjoin sends

---

android/app/build.gradle
e2e/routes.spec.ts
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/components/SyncContactsForm.tsx
src/i18n/en/translations.ts
src/logic/mutinyWalletSetup.ts
src/logic/waila.ts
src/routes/Send.tsx
src/routes/settings/ManageFederations.tsx
src/routes/settings/SyncNostrContacts.tsx
src/state/megaStore.tsx

Needs another round of full end to end testing first but getting the PR ready.

Prod v0.5.7

---

src/routes/Search.tsx

this uses the `s` (small) sized images from primal for contacts which should speed up loads. also because it's all from one origin I think the browser can batch these better.
question: is there a way to do the same with our own cache url?

use primal cdn for images

---

src/routes/Send.tsx

Saw a comment from the element chat where a bip21 had a lightning and pj component and the payjoin alert was displayed on both onchain and lightning. now payjoin alert only displays for onchain send.
[Kazam_screencast_00018.webm](https://github.com/MutinyWallet/mutiny-web/assets/108441023/33f3482a-5b14-48f0-b03c-7e15732fb4d9)

Payjoin alert only displayed when selecting onchain

---

e2e/fedimint.spec.ts
src/components/Amount.tsx
src/components/BalanceBox.tsx
src/i18n/en/translations.ts
src/routes/settings/ManageFederations.tsx

Closes #861 
This is a new prop! curious if @futurepaul wants me to not add a prop for this and go another approach

Add eSats for federation amounts

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/components/BalanceBox.tsx
src/components/Failure.tsx
src/components/ReceiveWarnings.tsx
src/components/index.ts
src/i18n/en/translations.ts
src/router.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/SwapLightning.tsx
src/routes/index.ts

This does a few refactors on common components. 
Does the swap and warns the user when a channel fee may be required. However one critical part is to use `estimate_sweep_federation_fee` once the user has selected the amount so that they can see the fee before they continue. Handles a bit different than the lightning->channel open flow does today which is hard for me to replicate. 
Relies on https://github.com/MutinyWallet/mutiny-node/pull/995

Fedimint sweep

---

src/routes/settings/ManageFederations.tsx

Refetch federation balances on updates

---

src/components/ChooseLanguage.tsx
src/components/index.ts
src/i18n/config.ts
src/i18n/en/translations.ts
src/router.tsx
src/routes/settings/Language.tsx
src/routes/settings/Root.tsx
src/routes/settings/index.ts
src/state/megaStore.tsx
src/utils/index.ts
src/utils/languages.ts

feat: add language selection on settings page

---

src/components/ChooseLanguage.tsx
src/components/ContactEditor.tsx
src/components/ContactViewer.tsx
src/components/MutinyPlusCta.tsx
src/i18n/en/translations.ts
src/routes/Search.tsx
src/routes/settings/Root.tsx
src/routes/settings/SyncNostrContacts.tsx
src/utils/languages.ts

Began working with someone to update the korean translation and figured I should go through and try to catch some stray text that was not using translation keys
also adds a small fallback enhancement for the language selector so that if there is no language state it checks if there is a i18n object instead of an empty string
```
selectedLanguage: state.lang ?? i18n.language
```

Update translation keys

---

.eslintrc.cjs
README.md
justfile
package.json
pnpm-lock.yaml
tools/internal-rules/.eslintrc.js
tools/internal-rules/lib/index.js
tools/internal-rules/lib/rules/check-i18n-keys.js
tools/internal-rules/package.json
tools/internal-rules/pnpm-lock.yaml

The way I went about this adds a whole new folder for internal eslint rules as I couldn't figure out how to add a single rule through a vite project. Additionally I could be far overcomplicating it with an eslint rule all together but I only found pre-made eslint plugins for json files not typescript files. At the end of the day the logic works but I would still like to try and simplify it.
ultimately this rule will be disabled exept when a translator wants to check their work they can switch it in the .eslintrc.cjs file from "off" => "warn" or whatever
while it doesn't use line numbers for the warning it specifies the key path for the dev to track down the missing or extra key

CI warnings for keys diff from fallback lang

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/logic/waila.ts
src/routes/Activity.tsx
src/routes/Search.tsx
vite.config.ts

needs https://github.com/MutinyWallet/mutiny-node/pull/1045

Merge waila

---

src/utils/fetchZaps.ts

Before we could never properly identify anon zaps because the `anon` tag we were getting from `findByTag` would be `undefined`  because there was no second element, even though it did have the `anon` tag. This just makes a dedicated function so it is easier to reason about.

Fix identifiying zap kind

---

README.md
src/i18n/en/translations.ts
src/router.tsx
src/routes/Redeem.tsx
src/routes/Send.tsx
src/routes/index.ts

I stole some logic from @tompro and rewrote the lnurlwithdrawal flow in a slightly simplified way with its own `/redeem` route. eventually we'll use this for cashu and oob ecash redeem but for now it's just lnurlwithdrawal
for some reason on my machine (idk if it's an internet thing?) the lnurlw on the faucet is super slow:
lnurl1dp68gurn8ghj7enpw43k2apwd46hg6tw09hx2apwvdhk6tmpwp5j7mrww4excac7utxd6
ben gave me one with a fixed amount though that works a lot faster: LNURL1DP68GURN8GHJ7MRWW4EXCTTNW3SKW6TWVUHX6AT5D9H8JAMPD3KX2APWVDHK6TMVDE6HYMRH9UCNQVPSXQZ6P5NU

add redeem route for lnulrwithdrawal

---

README.md
justfile
src/i18n/config.ts
src/i18n/es/translations.ts
src/utils/languages.ts

¡Hola!
I didn't use any automated tool nor AI, so this should be good quality :)
I also made the shebang in the i18n recipe more generic (wasn't working on NixOS).

Add Spanish

---

src/routes/Send.tsx

https://github.com/MutinyWallet/mutiny-node/pull/1040 broke anon zaps, now requires you to put the type of zap you're doing.
We should add public and private zaps eventually, but this fixes the functionality for now

Fix anonymous zaps

---

src/components/Reader.tsx

Was reading through the docs and seems like this would be beneficial 
https://github.com/nimiq/qr-scanner?tab=readme-ov-file#color-inverted-mode
potentially related to the user's issue in #935

Set inversion mode for scanner to 'both'

---

e2e/encrypt.spec.ts
public/i18n/en.json
public/i18n/es.json
public/i18n/ko.json

Since it doesn't prompt for setting a password, the 'change password' name is a bit incorrect. Just renamed to security in general.

Change password renamed to security

---

e2e/fedimint.spec.ts
public/i18n/en.json
public/i18n/es.json
src/components/BalanceBox.tsx
src/components/layout/Misc.tsx
src/routes/Profile.tsx
src/routes/settings/ManageFederations.tsx

for https://github.com/MutinyWallet/mutiny-node/pull/1060
works with my events i created, I don't think this will handle well if information is missing or if there is a ton of people recommending 
also need to do i18n and stuff too

Mint discoverability

---

src/components/EditProfileForm.tsx
src/router.tsx
src/routes/Chat.tsx
src/routes/settings/ImportProfile.tsx
src/routes/settings/NostrKeys.tsx
src/routes/settings/index.ts

I had intended to have this different route for nostr import after setup (that's why the form was already its own component), it's pretty confusing as-is.

Last UI fixes

---

src/root.css

fixes stuff like this:
text selection should still work in text boxes, but can't think of anything else that requires it

don't allow rando text selection

---

public/i18n/en.json
src/routes/settings/ManageFederations.tsx

closes #911 
I think we already handle this because the form is now hidden if you're in a federation. but this goes one extra step and hides the scanner and throws if an error if they somehow get that far

can't scan a federation when in a federation

---

ios/App/App.xcodeproj/project.pbxproj

We used to have testflight builds go out every merged PR, now they are failing because 1.6.1 was published in the app store
https://github.com/MutinyWallet/mutiny-web/actions/runs/8541656433/job/23401484406

Bump ios version

---

src/components/ActivityDetailsModal.tsx

this was showing the raw "i18n.t(..." string instead of the actual status value

fix unpaid status label

---

src/routes/settings/LightningAddress.tsx

this is my bad, we don't use the actual user's key for the nip05 we setup so we shouldn't set this. Maybe we'll fix in the backend and we can revert this

Don't set NIP-05 after lightning address

---

e2e/utils.ts
public/i18n/en.json
public/i18n/es.json
src/components/ImportNsecForm.tsx
src/components/layout/Button.tsx
src/router.tsx
src/routes/settings/ManageFederations.tsx
src/routes/setup/AddFederation.tsx
src/routes/setup/NewProfile.tsx
src/routes/setup/index.ts

pick a federation on setup

---

src/logic/mutinyWalletSetup.ts
src/state/megaStore.tsx

if mutiny-wasm panics during setup, that function never returns and no error is thrown, which stalls setup indefinitely. this sets up a timer so if it takes more than 60s mutiny-web will give up and show an error state
interestingly, functions seem to get polluted by a panicked wasm thing so throwing errors stops working as it should (they become uncaught)
this might help with #1070

timeout if load fails

---

e2e/roundtrip.spec.ts
src/state/megaStore.tsx

Someone reported the wallet was loading and then hitting the timeout thing after. I don't know how that would happen, it would seem somehow the timeout interval isn't being cleared. This makes it so even if the timeout is triggered, it won't do anything if the loading is done.

bump the timeout and make sure we're not done loading

---

e2e/fedimint.spec.ts
e2e/roundtrip.spec.ts
public/i18n/en.json
src/components/AmountEditable.tsx
src/components/IntegratedQR.tsx
src/components/ReceiveWarnings.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/workers/walletWorker.ts

No more bip21, just lightning and bitcoin address. need to test this out with ben's upcoming pr so we make sure we can handle all the potential scenarios

get rid of unified receive

---

package.json
pnpm-lock.yaml

We can worry about the android / ios version updates when we're ready for the real release.

Bump to mutiny-wasm v1.7.0-rc1

---

public/i18n/en.json
src/components/NWCEditor.tsx
src/routes/settings/Connections.tsx

Needs https://github.com/MutinyWallet/mutiny-node/pull/1173
There's nothing yet to enable a disabled profile, but there's a few things broken with this NWC connection page with it comes to our mutiny+ connection. This at least makes sure that profiles are "disabled/deleted" properly and it reflects it in the UI.

Show disabled NWCs again

---

public/i18n/en.json
src/components/ActivityDetailsModal.tsx
src/components/ReceiveWarnings.tsx
src/routes/Receive.tsx
src/routes/Send.tsx

Depends on https://github.com/MutinyWallet/mutiny-node/pull/1146
TODO:

Consider fedimint balance for on chain sends

---

e2e/roundtrip.spec.ts
public/i18n/en.json
src/components/Activity.tsx
src/components/AmountEditable.tsx
src/components/FederationPopup.tsx
src/components/index.ts
src/router.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/routes/Transfer.tsx
src/routes/index.ts
src/routes/settings/ManageFederations.tsx
src/state/megaStore.tsx
src/workers/walletWorker.ts

for #1128 
here's what I have so far. putting this here so @TonyGiorgio can see the logic I used to get the metadata

show federation expiration metadata

---

src/components/PendingNwc.tsx
src/components/SocialActionRow.tsx
src/routes/Search.tsx
src/workers/walletWorker.ts

in search of performance problems, this saves my wallet from timing out on a bunch of random profiles with broken image urls, plus all the work of fetching / serializing the profiles that do work
40 feels like a nice default

add limit for get_contacts_sorted

---

src/logic/mutinyWalletSetup.ts
src/state/megaStore.tsx

Before we would not set the session storage double init defense until after the wallet was initialized. This changes it to when we verify it isn't set, this way we immediately "claim the lock" instead of waiting until the wallet is loaded. Also cleaned up the error message to be more informative.
Not sure if this will actually fix anything but found this while trying to find init error

Immediately timestamp double init defense

---

src/state/megaStore.tsx
src/workers/walletWorker.ts

This was moved into the web worker which doesn't have access to this api call it seems

Move persistent storage init

---

ios/App/App/AppDelegate.swift

got this from https://stackoverflow.com/a/77107393
this seems to be working but I can only test with a version I built locally so would need to get it up in testflight to know for sure this works for all builds

make ios webview inspectable by safari in release

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/routes/SwapLightning.tsx
src/routes/Transfer.tsx
src/workers/walletWorker.ts

for https://github.com/MutinyWallet/mutiny-node/pull/1202

Fixes for olympus swaps

---

src/components/KitchenSink.tsx
src/routes/settings/Servers.tsx

First commit removes the LSP url from the servers page, this shouldn't be changed from here but from the admin page so we make sure we call the `change_lsp` function.
Second commit calls trim on all the lsp urls to help prevent issues

Remove LSP url from servers

---

src/routes/SwapLightning.tsx

Before we were showing this `swap_lightning.too_small` error, but this does not cover all the cases of errors we could get, instead just display the error we get from mutiny-wasm

Display proper swap error

---

e2e/roundtrip.spec.ts
src/routes/Send.tsx

only go back after send if it's a chat

---

.github/workflows/android-build.yml
.github/workflows/android-prod.yml
.github/workflows/android-staging.yml
.github/workflows/code-quality.yml
.github/workflows/ios-prod.yml
.github/workflows/ios-staging.yml
.github/workflows/playwright.yml
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/routes/settings/Servers.tsx
src/workers/walletWorker.ts

for https://github.com/MutinyWallet/mutiny-node/pull/1234

Correctly display the currently in use LSP

---

src/routes/Search.tsx

Search template is missing i18n translations.

fix: search template is missing translations references

---

package.json
pnpm-lock.yaml
src/components/Activity.tsx
src/components/SetupErrorDisplay.tsx
src/components/layout/Misc.tsx
src/routes/settings/EmergencyKit.tsx
src/routes/settings/ManageFederations.tsx
src/workers/walletWorker.ts

needs https://github.com/MutinyWallet/mutiny-node/pull/1239
to test you need to be in a federation and in safe mode, to enter safe mode to do so, go to `/?safe_mode=true`

Fedimint resync
