package-lock.json
package.json
src/App.tsx
src/components/Reader.tsx
src/index.css
src/routes/Home.tsx
src/routes/Scanner.tsx

I know this doesn't look like a lot of code for how long it's been but I def have tried a million things in the process to getting here

working qr scanner

---

.env
src/components/App.tsx
src/components/BalanceBox.tsx
src/components/NavBar.tsx
src/components/Reload.tsx
src/components/SafeArea.tsx
src/routes/Scanner.tsx
src/routes/Settings.tsx

makes desktop usage a little more tolerable
closes #14

Desktop a little bit

---

src/assets/icons/back.svg
src/assets/icons/big-receive.svg
src/assets/svg/Back.tsx
src/components/App.tsx
src/components/NavBar.tsx
src/components/layout/BackButton.tsx
src/components/layout/index.tsx
src/routes/Admin.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Settings.tsx

as per our most recent design meeting. decided to leave nav on desktop though because I find it pretty handy
https://user-images.githubusercontent.com/543668/233807736-5fcb42ef-77dd-40a8-8522-34bb08f40989.mov

hide nav on mobile

---

src/components/AmountEditable.tsx
src/components/layout/Radio.tsx
tailwind.config.cjs

fixes some of https://github.com/MutinyWallet/mutiny-web/issues/20

Fixes for amount editor

---

src/components/KitchenSink.tsx

Need #408 to be released first

Add lnurl auth tester to admin screen

---

src/components/Logs.tsx
src/components/SettingsStringsEditor.tsx
src/routes/Settings.tsx
src/utils/download.ts

I'll do a true #81 later but for now this makes it easy to get the logs

add log downloader

---

src/components/OnboardWarning.tsx

simplify backup header on mobile

---

src/components/Activity.tsx
src/components/waitlist/WaitlistForm.tsx
src/routes/Receive.tsx
src/routes/Send.tsx

closes #98 
closes #99
closes #115 
closes #108

Small UI may 12

---

src/components/AmountEditable.tsx
src/components/ContactEditor.tsx
src/components/ContactViewer.tsx
src/components/TagEditor.tsx
src/components/layout/FullscreenModal.tsx
src/components/layout/index.tsx
src/routes/Activity.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/styles/dialogs.ts
src/utils/tags.ts

no labels (for now)
also fixed some layout stuff need to test this pr on mobile before merging

simplified tagging

---

src/components/Activity.tsx
src/components/KitchenSink.tsx
src/logic/mutinyWalletSetup.ts
src/routes/Receive.tsx
src/routes/Redshift.tsx
src/utils/mempoolTxUrl.ts

change hardcoded signets to actual network

---

src/components/ImportExport.tsx

Imports need to be awaited, but can't happen with `onload` so that's why a bigger change was needed. Dont ask me how it works but it works now. Otherwise state would not fully load.

Make imports await on file upload

---

src/components/Activity.tsx

Use last_updated for sorting invoices

---

src/routes/Redshift.tsx

big diff is because of prettier, all I did was wrap the view in a div that overlays the controls

redshift coming soon

---

src/components/KitchenSink.tsx
src/components/NostrWalletConnectModal.tsx
src/state/megaStore.tsx

I just copy pasted the peer connection modal

Add Nostr wallet connect modal

---

src/components/App.tsx

closes #160 
(sorry diffs are going to be bad until I run the new prettier config on the whole dang repo)

feedback link

---

src/components/Amount.tsx
src/components/AmountEditable.tsx
src/components/CopyableQR.tsx
src/components/InfoBox.tsx
src/components/ShareCard.tsx
src/routes/Receive.tsx

warnings!
| | |
|--|--|
| <img width="316" alt="Screenshot 2023-05-29 at 1 29 36 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/409d05dc-b904-4c5a-900c-9febee5abe42"> | <img width="328" alt="Screenshot 2023-05-29 at 1 30 07 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/5ddfc299-8c8b-482b-ad14-eb058223fdc1"> |
| <img width="326" alt="Screenshot 2023-05-29 at 1 30 03 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/239a05df-4f9b-4fbe-bdc5-2248cda1c428"> | <img width="331" alt="Screenshot 2023-05-29 at 1 30 11 PM" src="https://github.com/MutinyWallet/mutiny-web/assets/543668/f6a97595-0013-49c9-9a3f-9d5aa19f0551"> |

fee and min amount warnings

---

package.json
pnpm-lock.yaml
src/components/BalanceBox.tsx
src/state/megaStore.tsx

Depends on a new cut of mutiny-wasm.
It's behaving much more fluid now. Excited about this.

Bump to 0.3.6 & no more syncing for the frontend

---

src/components/Activity.tsx
src/components/AmountEditable.tsx
src/components/BalanceBox.tsx
src/components/DetailsModal.tsx
src/routes/Swap.tsx
src/state/megaStore.tsx

also fixes a namechange in invoice struct

lengthen interval, set mainnet channel size to 50k

---

src/components/AmountEditable.tsx
src/utils/conversions.ts

amount input switchable to usd

---

.gitignore
e2e/load.spec.ts
package.json
playwright.config.ts
pnpm-lock.yaml
src/components/CopyableQR.tsx
src/components/layout/BackButton.tsx
src/routes/Receive.tsx

add simple load test and qr creation test

---

src/components/Activity.tsx
src/components/App.tsx
src/components/layout/Button.tsx
src/components/layout/index.tsx
src/components/waitlist/WaitlistAlreadyIn.tsx
src/routes/Activity.tsx
src/state/megaStore.tsx

this closes an IRL discussion where sync was causing lag on screens even that don't show activity. now activity only syncs on the home screen and activity screen
closes #212
this was built against mutiny-node master not sure if that's necessary tho actually

sync activity separately from regular sync

---

src/routes/Send.tsx

Closes #97 
initially opened a PR in #195 but i completely messed up the rebase, after several attempts to fix it i decided it would be easier to just close that PR

Send button now checks for insufficientFunds()

---

src/components/OnboardWarning.tsx

Add dismissed_backup to sessionStorage

---

src/components/AmountEditable.tsx
src/components/App.tsx
src/components/InfoBox.tsx
src/components/MoreInfoModal.tsx
src/components/layout/index.tsx
src/root.css
src/routes/Receive.tsx

add a "why" to fee warnings

---

src/routes/Receive.tsx
src/routes/Send.tsx

We'd always get this error log if we didn't tag a contact, now it'll skip the log
`Something went wrong with contact creation, proceeding anyway`

Skip error log if no contacts

---

src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/routes/Swap.tsx

don't show warnings if it's a swap

---

src/components/layout/Button.tsx
src/components/layout/index.tsx
src/routes/Storybook.tsx
tailwind.config.cjs

I had to change how disabled buttons work to make the spinner colored, which involved this big diff to the tailwind conf because apparently that hadn't been formatted yet
closes #177

remove bad "dark" mode for spinner (but don't desaturate the spinner)

---

src/components/ContactViewer.tsx
src/components/ResyncOnchain.tsx

Closes #243 
also a stray prettier formatting addition

X button and Escape now setIsEditing(false) when editing contacts

---

src/components/App.tsx
src/components/BetaWarningModal.tsx

this shows once on load and doesn't show again after it's dismissed

add beta warning

---

src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Swap.tsx

needs https://github.com/MutinyWallet/mutiny-node/pull/596 merged in
closes #62
closes #169

Send and swap max

---

src/components/Activity.tsx
src/components/DetailsModal.tsx
src/components/waitlist/Notes.tsx
src/state/megaStore.tsx

#148 
Not 100% sure that these type declarations are the correct way to fix these lints as I'm not totally familiar with handling Rust~Typescipt types
nostr-tools import SimplePool error

Fix type lint errors

---

src/components/SetupErrorDisplay.tsx
src/routes/index.tsx
src/state/megaStore.tsx

fix setup error precendence

---

src/assets/icons/currency-swap.svg
src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/styles/dialogs.ts

Closes #93
adds aditional functionality of amountEditable including fixed amounts add, holding backspace clears, and decimals for fiat are more accurate
now that I've seen the figma there are some changes i need to make / revert back to

Amount editable enhancement

---

src/components/KitchenSink.tsx

Add force close buttons

---

e2e/load.spec.ts

homescreen changes broke one of my tests. need to get these in CI eventually

test: don't expect headers that aren't there

---

src/components/Activity.tsx
src/components/DetailsModal.tsx
src/components/layout/index.tsx
src/routes/Scanner.tsx
src/routes/Send.tsx

had 10 minutes to contribute to something, closes https://github.com/MutinyWallet/mutiny-web/issues/267

Trim on paste

---

src/components/App.tsx
src/components/DecryptDialog.tsx
src/components/ImportExport.tsx
src/components/layout/TextField.tsx
src/components/layout/index.tsx
src/logic/mutinyWalletSetup.ts
src/routes/settings/Backup.tsx
src/routes/settings/Encrypt.tsx
src/routes/settings/Restore.tsx
src/routes/settings/index.tsx
src/state/megaStore.tsx
vite.config.ts

alright this is looking good imo. I tested setting a password, removing the password, exporting with / without encryption

encrypt / decrypt

---

src/components/AmountEditable.tsx
src/i18n/en/translations.ts

warn for large amounts

---

src/components/Activity.tsx
src/components/App.tsx
src/components/PendingNwc.tsx
src/routes/Activity.tsx
src/state/megaStore.tsx
src/utils/deepSignal.ts

this is yet another attempt to make activity sync non-blocking of the overall page load
seems to be working fine on my machine but I don't have enough activity to cause laggy loads
also I made it so pendingnwc updates the same way

async activity and nwc refresh

---

src/components/Toaster.tsx

closes #356 and #91, thanks @wbobeirne for explaining the fix
also fixed the close button size for toatss

fix toaster z-index

---

src/components/NavBar.tsx

closes #355 
a wise man once said:
> Pretty minor, but kinda annoying 🤷
just my speed!

fix navbar item padding

---

src/components/layout/index.tsx

add loading progress bar to all routes

---

src/components/AmountEditable.tsx
src/i18n/en/translations.ts

Warn if amount is over 21m bitcoin

---

package.json
src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/components/DeleteEverything.tsx
src/components/ImportExport.tsx
src/components/Logs.tsx
src/components/MoreInfoModal.tsx
src/components/Reader.tsx
src/components/SeedWords.tsx
src/components/layout/BackButton.tsx
src/components/layout/BackLink.tsx
src/components/layout/BackPop.tsx
src/components/layout/ProgressBar.tsx
src/components/layout/index.tsx
src/i18n/config.ts
src/i18n/en/translations.ts
src/i18n/i18next.d.ts
src/routes/Feedback.tsx
src/routes/Scanner.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/routes/[...404].tsx
src/routes/settings/Admin.tsx
src/routes/settings/Backup.tsx
src/routes/settings/Channels.tsx
src/routes/settings/Connections.tsx
src/routes/settings/EmergencyKit.tsx
src/routes/settings/Encrypt.tsx
src/routes/settings/index.tsx

Another pass at translations, this one has a large focus on settings
additionally a small error was fixed in `amountEditable.tsx` so that only holding the DEL key will erase the entire amount

Translation keys 2

---

src/logic/mutinyWalletSetup.ts

I don't understand what typescript does but this is a param that is needed

Add device lock param to setup mutiny

---

src/components/Fee.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Storybook.tsx
src/styles/dialogs.ts

fixing #363 was easier than I thought
while I was in there I fixed a bit of text alignment that was bothering me:
before:
after:

Design fixes: amount input scroll, fee text alignment

---

e2e/encrypt.spec.ts
src/routes/settings/Backup.tsx
src/routes/settings/Restore.tsx
src/routes/settings/index.tsx

This reverts commit 915b253db9dbd1c9dba4fa581a2f92b906c1f120.

Bring back encrypted local storage

---

src/components/OnboardWarning.tsx
src/i18n/en/translations.ts
src/i18n/ko/translations.ts
src/routes/settings/Encrypt.tsx
src/state/megaStore.tsx

until they back up we'll show them the notice, and now there's no dismiss button

show backup cta at launch

---

src/i18n/en/translations.ts
src/routes/settings/Plus.tsx
src/state/megaStore.tsx
src/utils/subscriptions.ts

rn it fails silently if you hit restore and get back an expired timestamp. now there's an error:

handle "restore" of expired subscriptions

---

src/routes/Send.tsx

Can use this lnurl to test `LNURL1DP68GURN8GHJ7MR9VAJKUEPWD3HXY6T5WVHXXMMD9AKXUATJD3CZ7M6ZFE58YCGE6FARZ`
This handles so if an lnurl has a fixed amount, we use that instead of asking the user to insert an amount.
We could also enforce the min and max but idk how to do that.

Handle amount in lnurl pay

---

android/app/build.gradle
package.json
pnpm-lock.yaml
src/components/App.tsx
src/components/BalanceBox.tsx
src/components/SetupErrorDisplay.tsx
src/i18n/en/translations.ts
src/logic/mutinyWalletSetup.ts
src/state/megaStore.tsx

if we're having connection problems there's a link to a safe mode `/?safe_mode=true` that disables lightning

add safe mode view

---

.gitignore

This app needs it the function in dev mode and yet it's not in the repo so I suppose you just forgot to add it to the gitignore file ?

Add .env to ignored files

---

package.json
packages/ui/rollup.config.js
packages/ui/tailwind.config.cjs

Tailwind config was missing the ui/src content so it was being lost when compiling.
Additionally, I had some trouble consistently building the ui package so I am changing the `build-submodules` script.
- looking into adding a watcher / input on the ui so that file changes there will restart the dev server ultimately removing the need for constant rebuilds
[Storybook Preview](https://ff5ed1f2.mutiny-web.pages.dev/storybook)

Fix ui lib

---

src/components/PendingNwc.tsx
src/i18n/en/translations.ts

https://github.com/MutinyWallet/mutiny-web/assets/543668/5b0aaf98-f1c0-4d51-8b17-6a533f20e915

approve all

---

src/i18n/en/translations.ts
src/i18n/ko/translations.ts
src/routes/settings/Connections.tsx

can test with this url: 
https://nwc-callback.mutiny-web.pages.dev/settings/connections?callbackUri=primal&name=Primal

Add nwc callback query parameters

---

android/app/capacitor.build.gradle
android/app/src/main/AndroidManifest.xml
android/capacitor.settings.gradle
package.json
pnpm-lock.yaml
src/components/ImportExport.tsx
src/components/Logs.tsx
src/utils/download.ts
vite.config.ts

Still need to do the code changes for it: https://capacitorjs.com/docs/apis/filesystem
fixes https://github.com/MutinyWallet/mutiny-web/issues/399

Android filesystem access

---

src/routes/Send.tsx

fix error while sending

---

android/app/src/main/AndroidManifest.xml

Should allow the app to have app.mutinywallet.com be autoverified
turns out the data actually doesn't need to be in separate intents
make sure we are using the correct fingerprint for our release in assetlinks.json

Autoverify open by default links

---

src/i18n/en/translations.ts
src/routes/settings/Channels.tsx

Add channel reserve to lightning channels screen

---

src/components/Logs.tsx
src/i18n/en/translations.ts

Fixes #513 
Requires https://github.com/MutinyWallet/mutiny-node/pull/751

Fix downloading logs with a password set

---

src/components/ActivityItem.tsx
src/components/Amount.tsx
src/components/AmountCard.tsx
src/components/AmountEditable.tsx
src/components/BalanceBox.tsx
src/components/ChooseCurrency.tsx
src/components/index.ts
src/components/layout/SelectField.tsx
src/components/layout/index.ts
src/i18n/en/translations.ts
src/routes/settings/Currency.tsx
src/routes/settings/index.tsx
src/state/megaStore.tsx
src/utils/conversions.ts

After https://github.com/MutinyWallet/mutiny-node/pull/736 we should be able to choose any currency we want

Add option to select desired fiat currency

---

src/components/layout/ExternalLink.tsx
src/i18n/en/translations.ts
src/routes/settings/index.tsx
vite.config.ts

@futurepaul Happy to make it a full clickable settingsLink if you think it should live separately

Add version to bottom of settings

---

src/components/layout/Misc.tsx
src/components/layout/Radio.tsx
src/i18n/en/translations.ts
src/routes/Receive.tsx
src/routes/Redshift.tsx
src/routes/Send.tsx
src/state/megaStore.tsx

option to remember invoice type choice

---

.dockerignore
.github/workflows/docker.yml
Dockerfile

wanna add CI to publish the container

Dockerfile

---

src/routes/settings/Restore.tsx

Was trying to paste my seed words but getting errors with a trailing space

Trim pasted seed words

---

.github/workflows/docker.yml
Dockerfile

Also correctly sets the RGS url properly

Arm64 docker build

---

src/components/layout/Radio.tsx

the whole button of the `StyledRadioGroup.tsx` is now selectable

StyledRadiogroup padding

---

package.json
pnpm-lock.yaml
src/routes/Send.tsx

with ldk 117 I added the ability to add a message to keysends, this just fixes the api call and puts a todo for us to eventually add
needs https://github.com/MutinyWallet/mutiny-node/pull/772/

Update needed for ldk-117

---

src/i18n/en/translations.ts
src/routes/Receive.tsx

Closes #600 
~~Should I make this error catch as granular as it is or should I just return all possible errors from this particular catch like so and then log out the specifics? Don't know how else the logic above this catch could fail...~~ I added some new error messages for other possible failures

Error catch receive amount too low

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
package.json
pnpm-lock.yaml
src/components/PendingNwc.tsx
src/routes/Receive.tsx
src/routes/Send.tsx
src/routes/Swap.tsx
src/routes/settings/Plus.tsx
src/utils/index.ts
src/utils/vibrate.ts
vite.config.ts

Vibrate on successful send, receive, channel open

---

src/i18n/en/translations.ts
src/routes/settings/Gift.tsx
src/routes/settings/index.tsx

Enable gifting on christmas

---

android/app/build.gradle
package.json
pnpm-lock.yaml
src/components/PendingNwc.tsx
src/routes/settings/Plus.tsx

Needs https://github.com/MutinyWallet/mutiny-node/pull/801
makes it so we do deny all in a batch

Better deny all nwc

---

android/app/build.gradle
src/components/NWCBudgetEditor.tsx
src/routes/settings/Connections.tsx

also made it so auto approve is checked by default if there's an amount or interval in the incoming search params

include nwc string in url callback

---

src/components/ChooseCurrency.tsx

Add AUD currency

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/App/App.entitlements
ios/App/fastlane/Fastfile
ios/App/fastlane/README.md
public/.well-known/apple-app-site-association

this involves a cert update (because there's a new "permission") so hopefully our fastlane config holds up...
https://capacitorjs.com/docs/guides/deep-links

add domain association for ios

---

ios/App/fastlane/Fastfile
src/routes/settings/Connections.tsx

closes #708 
this is one of those "I don't know why it was working before" kind of bugs but seems solid now. basically we just refetch after edits, instead of constantly

don't refetch connections every sync

---

android/app/build.gradle

bump android to 0.4.34

---

.github/workflows/playwright.yml
android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
ios/App/App/App.entitlements
ios/App/fastlane/Fastfile
ios/App/fastlane/README.md
public/.well-known/apple-app-site-association
src/routes/settings/Connections.tsx
src/utils/fetchZaps.ts

This is in order to test the domain association

Deploy to prod

---

android/app/capacitor.build.gradle
android/capacitor.settings.gradle
ios/App/App/Info.plist
ios/App/Podfile
ios/App/Podfile.lock
package.json
pnpm-lock.yaml
src/components/Toaster.tsx
src/i18n/en/translations.ts
src/routes/settings/Connections.tsx
src/utils/openLinkProgrammatically.ts

closes #686, thx for pointing out this capacitor library @TonyGiorgio 
also remove the hard-coded primal option... on android it prompts anyway
tested on ios and android and web

use capacitor AppLauncher instead of Browser

---

src/routes/settings/Gift.tsx
src/routes/settings/Root.tsx
src/utils/subscriptions.ts

Can test by changing your system clock, works for me when changing to this thursday!

Free gifting on thanksgiving

---

src/state/megaStore.tsx

@benthecarman had a long timeout... I normally get 403s so haven't noticed this as a problem

check price after startup

---

src/routes/settings/Plus.tsx
src/state/megaStore.tsx

this was pretty easy mostly just deleting code
(btw reason for duplication between checkForSubscription and the logic in setup is there's no mutiny_wallet object yet for the action version to use)

check for subscribed on startup

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/i18n/en/translations.ts
src/routes/Send.tsx
src/routes/settings/Channels.tsx

needs [#876](https://github.com/MutinyWallet/mutiny-node/pull/876)

handle channel reserve error

---

src/routes/Send.tsx

closes https://github.com/MutinyWallet/mutiny-web/issues/723
(still need to work on `lightning:` kind of handlers but this is a step towards that)

handle invoice query param in send

---

src/routes/settings/Connections.tsx

catch nwa error throw

---

src/components/KitchenSink.tsx

Refresh peers on disconnect

---

src/components/ActivityItem.tsx
tailwind.config.cjs

Yellow pending status

---

.env.mainnet
.env.signet

Often can be tricky to remember all the different changes needed for signet vs mainnet, this should make it easier for people

Add signet and mainnet .env files

---

src/i18n/en/translations.ts
src/routes/Receive.tsx
src/routes/Send.tsx

Closes #820
Closes #681
Also fixes handling expired invoices
Should be the last thing needed to close #569

Fix editing amount on receive screen

---

src/components/LabelCircle.tsx
src/routes/Search.tsx
src/utils/debounce.ts
src/utils/index.ts

search is a lot less buggy now with losing focus. also don't need to show contacts at all once we know it's an invoice or on-chain address

Not always contacts

---

src/routes/settings/ManageFederations.tsx

Not sure if the switch / match is the cleanest way to do this but it works :man_shrugging:

Display individual fedimint balances

---

src/components/ActivityDetailsModal.tsx

found while testing some stuff

Fix Switch/Show order

---

public/i18n/en.json
src/routes/settings/Servers.tsx

Some people keep trying this and borking their wallet. This will give them an error for tor support

Add error message for tor urls

---

src/components/NostrActivity.tsx
src/components/SyncContactsForm.tsx
src/state/megaStore.tsx

this will fix the zap feed
closes https://github.com/MutinyWallet/mutiny-node/issues/1088

Remove local storage npub

---

public/i18n/en.json
src/components/BigMoney.tsx
src/components/FeeDisplay.tsx
src/components/layout/Misc.tsx
src/routes/Receive.tsx

200k sat warning

---

src/components/ImportNsecForm.tsx
src/components/SimpleInput.tsx

hide password for nsec input

---

src/routes/Profile.tsx

Without then when I scan the qr it tries to send an email

Add `lightning:` prefix to ln addr qr code

---

package.json
pnpm-lock.yaml
public/i18n/en.json
src/components/SocialActionRow.tsx
src/logic/mutinyWalletSetup.ts
src/routes/Profile.tsx
src/routes/Search.tsx
src/routes/settings/ImportProfile.tsx
src/routes/settings/NostrKeys.tsx
src/routes/setup/ImportProfile.tsx
src/routes/setup/NewProfile.tsx

needs https://github.com/MutinyWallet/mutiny-node/pull/1096

add delete nostr profile ability

---

src/components/PendingNwc.tsx

show profile images for requests

---

public/i18n/en.json
src/components/GenericItem.tsx

@benthecarman mentioned this was a little confusing without the text to say what it means

"expires in" for pending requests

---

src/components/Activity.tsx

need to add proper pagination in the future

Only get first 50 activity items

---

src/state/megaStore.tsx

mutiny-node does this automatically now
potentially related to #996

Remove sync_nostr call on startup

---

.github/workflows/ios-prod.yml

Need this to make an arbitrary testflight build on any branch

Allow making testflight release on branches

---

src/components/SocialActionRow.tsx
src/routes/Search.tsx

Closes #963 
Not really sure if `actions.handleIncomingString` is the correct thing to be calling here

Handle contacts with no npub/lnurl

---

src/components/HomePrompt.tsx

sorry @johncantrell97 it was easier to do this than rebase / change your version. works on my machine but if you can test as well that would be great and we can get this in

set lsps settings via url query params

---

src/components/layout/TextField.tsx
src/routes/Feedback.tsx
src/routes/settings/LightningAddress.tsx

make sure lightning address is lowercase

---

src/routes/Send.tsx

We were only doing this for zaps but we can pass it along for lnurls too

Always pass along lnurl comment

---

src/logic/errorDispatch.ts
src/routes/settings/ManageFederations.tsx

I tested by doing `inviteCodes.unshift("invalid")`  before the for loop

Try each federation guardian when joining

---

src/components/Activity.tsx

closes #1014 
reworked how activity is being fetched, because it was NOT caching, and then used the `cache` function (https://github.com/solidjs/solid-router?tab=readme-ov-file#cache) to actually cache profile fetches

cache nostr profile fetching in activity view

---

src/logic/mutinyWalletSetup.ts
src/state/megaStore.tsx

if you add `?skip_setup=true` to the url it'll now skip our walkthrough, this is for the c= guys

Skip setup if flag set & set LSPS Config on startup

---

src/components/layout/Misc.tsx

fix style typo

---

src/routes/Chat.tsx

allow text selection in dms

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/routes/setup/NewProfile.tsx

needs https://github.com/MutinyWallet/mutiny-node/pull/1125

switch to setup_new_profile

---

public/i18n/en.json
src/components/FederationInviteShower.tsx
src/components/index.ts
src/routes/settings/ManageFederations.tsx

@TonyGiorgio and I discussed this over steak tartare

invite codes and list federations even if you're in one

---

src/components/ReceiveWarnings.tsx

closes #1034 but needs something from mutiny node I believe

don't warn about 100k if using LSPS

---

public/i18n/en.json
src/components/layout/LoadingSpinner.tsx
src/components/layout/SubtleButton.tsx
src/components/layout/index.ts
src/routes/settings/ManageFederations.tsx

for https://github.com/MutinyWallet/mutiny-node/pull/1127
I just put a big red button, probably a prettier way to do it

Unrecommend federations

---

src/routes/Chat.tsx
src/routes/Send.tsx

fixes unleashed.chat @benthecarman

handle invoices inside of message

---

justfile

I do a lot of switching networks for certain tests so this just saves me some copy / pasting

just commands for switching network

---

src/components/Activity.tsx
src/components/GenericItem.tsx
src/routes/setup/AddFederation.tsx

closes #967 
thankfully the logic for showing this was still in there, they just weren't clickable

show channel close details

---

.github/workflows/ios-prod.yml
.github/workflows/ios-staging.yml
ios/App/Gemfile.lock
public/i18n/en.json
src/routes/Receive.tsx

we're removing the 200k limit, now the info box just lets them know it will go into a federation

remove 200k language

---

src/components/BalanceBox.tsx

restore swap functionality

---

public/i18n/en.json

Correct "each one is ran by.. " to "each one is run by"

Correct grammar of federations description

---

public/i18n/en.json
src/components/EditProfileForm.tsx
src/routes/Profile.tsx
src/routes/settings/LightningAddress.tsx
src/routes/settings/Plus.tsx
src/routes/setup/NewProfile.tsx

don't hide lightning address CTA if not in federation

---

src/components/Activity.tsx

move backup cta to top

---

src/routes/Swap.tsx

bug in the worker refactor
decided this was a good time to get rid of the extra logic for signet. no need to complicate things

fix swap amount editor breaking

---

src/components/Activity.tsx

remove an unnecessary cache layer for contacts that was doing bad things

---

src/components/SocialActionRow.tsx

Filter self from social row

---

src/components/Activity.tsx
src/utils/fetchZaps.ts

Special case zapple pay for friends tab

---

src/components/PendingNwc.tsx

this file needed some cleanup so I'm doing this one and closing #1073

show "edit" on nwc button if they already have nwc profiles

---

src/routes/Receive.tsx

Fix amountless onchain

---

src/routes/Receive.tsx

a close personal acquaintance was confused by this

remove "keep open" warning for on-chain receives

---

android/app/build.gradle
ios/App/App.xcodeproj/project.pbxproj
package.json
pnpm-lock.yaml
src/workers/walletWorker.ts

needs next mutiny node release

Don't use constructor, use new function

---

src/components/HomeBalance.tsx

don't show balance until we're done loading

---

public/i18n/en.json
src/routes/setup/Root.tsx

pushing to someone else's branch stresses me out, and also need some discussion here:
I'd prefer to not have this on the setup screen, but I'm willing to go with it if you feel strongly it should be there. However, I'm pretty strongly against it being default on.
This pr has some styling, a typo fix, and defaults to off.

default false diagnostics, style the welcome

---

e2e/encrypt.spec.ts
e2e/utils.ts
public/i18n/en.json
src/components/Activity.tsx
src/components/ShutdownPopup.tsx
src/components/index.ts
src/state/megaStore.tsx

add shutdown popup warning

---

src/routes/settings/Servers.tsx

this is a gross way to code this but felt the easiest to reason about so I went with it

hide voltage lsp option
